//! One host's patch file: the `patch` documents aimed at it, then an `ExtensionServiceConfig`
//! document for each of `awg`, `router` and - if the host gets a ruleset - `nftables`, carrying
//! that daemon's config once the daemon's own `validate()` accepts it.

use crate::render;
use crate::secrets::ResolvedSecrets;
use crate::slipmesh_file::SlipmeshFile;
use anyhow::{Context, Result};

/// What opens every patch file this tool writes.
pub const HEADER: &str =
    "# Generated by slipmesh-taloscfg from slipmesh.yaml - edit that file, not this one.\n";

#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
struct ExtensionServiceConfig<'a> {
    api_version: &'a str,
    kind: &'a str,
    name: &'a str,
    config_files: [ConfigFile<'a>; 1],
}

#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
struct ConfigFile<'a> {
    mount_path: &'a str,
    content: &'a str,
}

/// Renders one owned `ExtensionServiceConfig` document: `name`/`mountPath` fixed by convention,
/// `inner_yaml` - the daemon's own already-serialized config - as the file's content.
fn render_extension_service_document(
    name: &str,
    mount_path: &str,
    inner_yaml: &str,
) -> Result<String> {
    let document = ExtensionServiceConfig {
        api_version: "v1alpha1",
        kind: "ExtensionServiceConfig",
        name,
        config_files: [ConfigFile {
            mount_path,
            content: inner_yaml,
        }],
    };
    yaml_serde::to_string(&document).context("serializing an ExtensionServiceConfig document")
}

/// The patch file of `host`, as the text written to disk.
pub fn render(file: &SlipmeshFile, resolved: &ResolvedSecrets, host: &str) -> Result<String> {
    let model = file.effective_for(host)?;
    let awg_cfg = render::render_awg_config(&model, host, resolved)
        .with_context(|| format!("rendering awg config for node {host:?}"))?;
    awg::config::validate(&awg_cfg)
        .with_context(|| format!("rendered awg config for node {host:?} is invalid"))?;
    let router_cfg = render::render_router_config(&model, host)
        .with_context(|| format!("rendering router config for node {host:?}"))?;
    router::config::validate(&router_cfg)
        .with_context(|| format!("rendered router config for node {host:?} is invalid"))?;
    let nftables_cfg = render::render_nftables_config(&model);
    if let Some(cfg) = &nftables_cfg {
        nftables::config::validate(cfg)
            .with_context(|| format!("rendered nftables config for node {host:?} is invalid"))?;
    }

    let patches: Vec<String> = file
        .patches_for(host)?
        .into_iter()
        .map(|patch| patch.text)
        .collect();

    let mut generated = vec![
        render_extension_service_document(
            "awg",
            "/etc/talos-extensions/awg.yaml",
            &yaml_serde::to_string(&awg_cfg)?,
        )?,
        render_extension_service_document(
            "router",
            "/etc/talos-extensions/router.yaml",
            &yaml_serde::to_string(&router_cfg)?,
        )?,
    ];
    if let Some(cfg) = &nftables_cfg {
        generated.push(render_extension_service_document(
            "nftables",
            "/etc/talos-extensions/nftables.yaml",
            &yaml_serde::to_string(cfg)?,
        )?);
    }

    Ok(format!(
        "{HEADER}{}\n",
        [patches, generated].concat().join("\n---\n")
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::secrets;

    #[test]
    fn render_extension_service_document_is_the_serializers_output() {
        let inner = "interfaces:\n- name: mesh-b\n  listen_port: 51820\n";
        let doc = render_extension_service_document("awg", "/etc/talos-extensions/awg.yaml", inner)
            .unwrap();
        assert_eq!(
            doc,
            "apiVersion: v1alpha1\nkind: ExtensionServiceConfig\nname: awg\nconfigFiles:\n- mountPath: /etc/talos-extensions/awg.yaml\n  content: |\n    interfaces:\n    - name: mesh-b\n      listen_port: 51820\n"
        );
    }

    /// The `ExtensionServiceConfig` named `name` among the documents of `file`, if there is one.
    fn generated_document(file: &str, name: &str) -> Option<yaml_serde::Value> {
        use serde::Deserialize;
        yaml_serde::Deserializer::from_str(file)
            .map(|document| yaml_serde::Value::deserialize(document).unwrap())
            .find(|value| value["kind"] == "ExtensionServiceConfig" && value["name"] == name)
    }

    fn content(document: &yaml_serde::Value) -> &str {
        document["configFiles"][0]["content"].as_str().unwrap()
    }

    #[test]
    fn render_extension_service_document_carries_the_daemon_config_as_its_content() {
        let inner = yaml_serde::to_string(&nftables::config::NftablesConfig {
            ruleset: "table inet x {}".to_string(),
        })
        .unwrap();
        let doc = render_extension_service_document(
            "nftables",
            "/etc/talos-extensions/nftables.yaml",
            &inner,
        )
        .unwrap();
        let found = generated_document(&doc, "nftables").unwrap();
        let cfg: nftables::config::NftablesConfig = yaml_serde::from_str(content(&found)).unwrap();
        assert_eq!(cfg.ruleset, "table inet x {}");
    }

    const SLIPMESH: &str = r#"slipmesh:
  kind: network
cluster:
  bgp_as: 64512
  loopback_networks: {ipv4: "10.62.0.0/16", ipv6: "fd00:62::/32"}
nodes:
  - {name: a, node_id: "10.62.0.1", endpoint: "192.0.2.10"}
  - {name: b, node_id: "10.62.0.2", endpoint: "192.0.2.11"}
mesh:
  links:
    - {pair: [a, b], port: 51820}
---
slipmesh:
  kind: patch
  include: [a]
apiVersion: v1alpha1
kind: UnattendedInstallConfig
installer:
    disk: /dev/vda
---
slipmesh:
  kind: nftables
  exclude: [b]
ruleset: "table inet x {}"
"#;

    fn rendered(host: &str) -> String {
        let file = SlipmeshFile::parse(SLIPMESH).unwrap();
        let (resolved, _) = secrets::resolve(file.topology());
        render(&file, &resolved, host).unwrap()
    }

    #[test]
    fn a_host_gets_its_patches_then_its_generated_documents() {
        let a = rendered("a");
        assert!(a.starts_with(HEADER), "{a}");
        let disk = a.find("disk: /dev/vda").expect(&a);
        assert!(disk < a.find("name: awg").unwrap(), "{a}");
        assert!(content(&generated_document(&a, "awg").unwrap()).contains("mesh-b"));
        assert!(generated_document(&a, "router").is_some());
        assert!(generated_document(&a, "nftables").is_some());
    }

    #[test]
    fn a_host_gets_only_the_documents_aimed_at_it() {
        let b = rendered("b");
        assert!(b.starts_with(HEADER), "{b}");
        assert!(!b.contains("disk:"), "{b}");
        assert!(generated_document(&b, "awg").is_some());
        assert!(generated_document(&b, "nftables").is_none());
    }

    #[test]
    fn a_config_the_daemon_rejects_is_not_rendered() {
        let raw = SLIPMESH.replace("table inet x {}", "table inet t { {{ bogus }} }");
        let file = SlipmeshFile::parse(&raw).unwrap();
        let (resolved, _) = secrets::resolve(file.topology());
        let err = render(&file, &resolved, "a").unwrap_err();
        assert!(format!("{err:#}").contains("nftables"), "{err:#}");
    }
}
