log stderr { info, remote, warning, error, auth, fatal, bug };
router id {{ loopback }};
protocol device {
}
protocol direct direct1 {
    interface "{{ router_loopback_iface }}";
    ipv4 { import all; };
}
{%- for iface in direct_interfaces %}
protocol direct direct_{{ iface.protocol_id }} {
    interface {{ iface.pattern }};
    ipv4 { import all; };
}
{%- endfor %}
protocol kernel {
    ipv4 {
{%- if !learn.is_empty() %}
        import filter {
            if net ~ [ {{ learn|join(", ") }} ] then accept;
            reject;
        };
{%- endif %}
        export filter {
            if source = RTS_BGP then {
                krt_prefsrc = {{ loopback }};
                accept;
            }
            if proto = "ANNOUNCE" then {
                krt_prefsrc = {{ loopback }};
                accept;
            }
            reject;
        };
    };
{%- if learn.is_empty() %}
    learn no;
{%- else %}
    learn all;
{%- endif %}
}
protocol kernel {
    ipv6 {
        export filter {
            if source = RTS_OSPF || source = RTS_OSPF_IA ||
               source = RTS_OSPF_EXT1 || source = RTS_OSPF_EXT2 then accept;
            reject;
        };
    };
}
protocol ospf v3 mesh6 {
    ipv6 {
        import all;
        export none;
    };
    area 0 {
        interface "{{ router_loopback_iface }}" { stub yes; };
{%- for iface in ospf_interfaces %}
        interface {{ iface }} { type ptp; };
{%- endfor %}
    };
}
{%- if !bypass.is_empty() %}
protocol static BYPASS {
    ipv4 { import all; };
{%- for r in bypass %}
    route {{ r.net }} blackhole; # {{ r.label }}
{%- endfor %}
}
{%- endif %}
{%- if !announce.is_empty() %}
protocol static ANNOUNCE {
    ipv4 { import all; };
{%- for r in announce %}
    route {{ r.net }} via "{{ router_loopback_iface }}"; # {{ r.label }}
{%- endfor %}
}
{%- endif %}
{%- for peer in bgp_peers %}
protocol bgp ibgp6_{{ peer.protocol_id }} {
    local {{ ipv6_loopback }} as {{ as_number }};
    neighbor {{ peer.address }} as {{ as_number }};
    multihop;
    ipv4 {
        extended next hop on;
        import all;
        export filter {
            if source = RTS_DEVICE then accept;
            if source = RTS_STATIC then accept;
{%- if !learn.is_empty() %}
            if source = RTS_INHERIT then accept;
{%- endif %}
            reject;
        };
        next hop self;
    };
}
{%- endfor %}
